
upstream news_cluster {
    server backend1:3000;
    server backend2:3000;
    server backend3:3000;
}


server {
    listen 80;
    server_name reports.baby www.reports.baby;
    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;
    server_name reports.baby www.reports.baby;
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/reports_baby.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;


    location /api {
        proxy_pass http://news_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    location /write {
        root /usr/share/nginx/html;
        try_files $uri /write/write.html;
    }

    location /login {
        root /usr/share/nginx/html;
        try_files $uri /login/login.html;
    }

    location /delete {
       root /usr/share/nginx/html;
       try_files $uri /delete/delete.html; 
    }

    location /images {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }
}


