
server {

    listen 5000;
    client_max_body_size 20M;
    
    location /api {
        resolver 127.0.0.11 valid=10s;
        set $backend_servers http://backend:3000;
        proxy_pass $backend_servers;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /reader {
        alias /usr/share/nginx/html/reader-frontend/;
        try_files $uri /reader/index.html;
    }

    location /writer {
        alias /usr/share/nginx/html/writer-frontend/;
        try_files $uri /writer/index.html;
    }

    location /images {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }
}


